import dotenv from 'dotenv'

dotenv.config()

const {
  OAUTH_GOOGLE_OAUTH_CLIENT_ID,
  OAUTH_GOOGLE_OAUTH_AUTH_URL,
  OAUTH_GOOGLE_OAUTH_REDIRECT_SERVER,
  OAUTH_GOOGLE_TOKEN_URL,
  OAUTH_GOOGLE_CLIENT_SECRET
} = process.env as { [key: string]: string }

export const OAUTH_2_GOOGLE = {
  CLIENT_ID: OAUTH_GOOGLE_OAUTH_CLIENT_ID,
  AUTH_URL: OAUTH_GOOGLE_OAUTH_AUTH_URL,
  REDIRECT_SERVER: OAUTH_GOOGLE_OAUTH_REDIRECT_SERVER,
  TOKEN_URL: OAUTH_GOOGLE_TOKEN_URL,
  CLINET_SECRET: OAUTH_GOOGLE_CLIENT_SECRET
} as const
